name: Update README Glyph

on: 
  push:
    branches:
      - main

jobs:
  update-glyph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for Glyph generation

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Generate Glyph
        run: python backend/generate_glyph.py

      - name: Commit and push Glyph to README
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add glyphs/latest_glyph.svg
          git commit -m "Update README Glyph [skip ci]"
          git push
